import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static const String _langKey = 'app_language';
  static String _currentLanguage = 'en';

  static String get currentLanguage => _currentLanguage;
  static bool get isUrdu => _currentLanguage == 'ur';

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_langKey) ?? 'en';
  }

  static Future<void> setLanguage(String lang) async {
    _currentLanguage = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_langKey, lang);
  }

  static const Map<String, String> _strings = {
    // ── Navigation ──
    'nav_home_en': 'Home',
    'nav_home_ur': 'ہوم',
    'nav_inquiries_en': 'Inquiries',
    'nav_inquiries_ur': 'انکوائریز',
    'nav_profile_en': 'Profile',
    'nav_profile_ur': 'پروفائل',
    'nav_shop_en': 'Shop',
    'nav_shop_ur': 'شاپ',
    'nav_settings_en': 'Settings',
    'nav_settings_ur': 'ترتیبات',

    // ── Common ──
    'cancel_en': 'Cancel',
    'cancel_ur': 'منسوخ کریں',
    'delete_en': 'Delete',
    'delete_ur': 'حذف کریں',
    'edit_en': 'Edit',
    'edit_ur': 'ترمیم',
    'retry_en': 'Retry',
    'retry_ur': 'دوبارہ کوشش کریں',
    'submit_en': 'Submit',
    'submit_ur': 'جمع کریں',
    'close_en': 'Close',
    'close_ur': 'بند کریں',
    'back_en': 'Back',
    'back_ur': 'واپس',
    'yes_en': 'Yes',
    'yes_ur': 'ہاں',
    'no_en': 'No',
    'no_ur': 'نہیں',
    'all_en': 'All',
    'all_ur': 'سب',
    'new_en': 'New',
    'new_ur': 'نیا',
    'view_en': 'View',
    'view_ur': 'دیکھیں',
    'required_en': 'Required',
    'required_ur': 'ضروری',
    'error_en': 'Error',
    'error_ur': 'خرابی',
    'failed_en': 'Failed',
    'failed_ur': 'ناکام',

    // ── Auth ──
    'welcome_back_en': 'Welcome Back',
    'welcome_back_ur': 'خوش آمدید',
    'sign_in_continue_en': 'Sign in to continue to your AI portal',
    'sign_in_continue_ur': 'اپنے AI پورٹل میں جاری رکھنے کے لیے سائن ان کریں',
    'email_address_en': 'EMAIL ADDRESS',
    'email_address_ur': 'ای میل ایڈریس',
    'email_hint_en': 'name@company.com',
    'email_hint_ur': 'name@company.com',
    'password_en': 'PASSWORD',
    'password_ur': 'پاسورڈ',
    'forgot_password_en': 'Forgot Password?',
    'forgot_password_ur': 'پاسورڈ بھول گئے؟',
    'sign_in_en': 'Sign In',
    'sign_in_ur': 'سائن ان',
    'dont_have_account_en': "Don't have an account? ",
    'dont_have_account_ur': 'اکاؤنٹ نہیں ہے؟ ',
    'sign_up_en': 'Sign Up',
    'sign_up_ur': 'سائن اپ',
    'create_account_en': 'Create Account',
    'create_account_ur': 'اکاؤنٹ بنائیں',
    'join_future_en': 'Join the future of AI-driven business',
    'join_future_ur': 'AI سے چلنے والے کاروبار کے مستقبل میں شامل ہوں',
    'full_name_en': 'FULL NAME',
    'full_name_ur': 'پورا نام',
    'name_hint_en': 'John Doe',
    'name_hint_ur': 'علی رضا',
    'work_email_en': 'WORK EMAIL',
    'work_email_ur': 'کام کا ای میل',
    'password_hint_en': '••••••••',
    'password_hint_ur': '••••••••',
    'i_agree_to_en': 'I agree to the ',
    'i_agree_to_ur': 'میں اس کی سہمتی دیتا ہوں ',
    'and_en': ' and ',
    'and_ur': ' اور ',
    'already_have_account_en': 'Already have an account? ',
    'already_have_account_ur': 'پہلے سے اکاؤنٹ ہے؟ ',
    'log_in_en': 'Log In',
    'log_in_ur': 'لاگ ان',
    'otp_resent_en': 'OTP resent',
    'otp_resent_ur': 'OTP دوبارہ بھیج دیا',
    'resend_otp_en': 'Resend OTP',
    'resend_otp_ur': 'OTP دوبارہ بھیجیں',

    // ── Two-Factor Auth ──
    'two_factor_en': 'Two-Factor Authentication',
    'two_factor_ur': 'دو مرحلہ تصدیق',
    'enter_otp_sent_en': 'Enter the 6-digit code sent to',
    'enter_otp_sent_ur': 'بھیجے گئے 6 ہندسوں کا کوڈ درج کریں',
    'verify_en': 'Verify',
    'verify_ur': 'تصدیق کریں',

    // ── Forgot / Reset Password ──
    'forgot_password_title_en': 'Forgot Password?',
    'forgot_password_title_ur': 'پاسورڈ بھول گئے؟',
    'forgot_password_desc_en': "Enter your email and we'll send you an OTP to reset your password.",
    'forgot_password_desc_ur': 'اپنا ای میل درج کریں اور ہم آپ کو پاسورڈ ری سیٹ کرنے کے لیے OTP بھیجیں گے۔',
    'otp_sent_email_en': 'OTP sent to your email',
    'otp_sent_email_ur': 'OTP آپ کے ای میل پر بھیج دیا',
    'send_otp_en': 'Send OTP',
    'send_otp_ur': 'OTP بھیجیں',
    'remember_password_en': 'Remember your password? ',
    'remember_password_ur': 'پاسورڈ یاد ہے؟ ',
    'new_password_en': 'New Password',
    'new_password_ur': 'نیا پاسورڈ',
    'new_password_desc_en': 'Create a new password for your account.',
    'new_password_desc_ur': 'اپنے اکاؤنٹ کے لیے نیا پاسورڈ بنائیں۔',
    'confirm_password_en': 'CONFIRM PASSWORD',
    'confirm_password_ur': 'پاسورڈ کی تصدیق',
    'passwords_not_match_en': 'Passwords do not match',
    'passwords_not_match_ur': 'پاسورڈ مماثل نہیں ہیں',
    'password_reset_success_en': 'Password reset successful!',
    'password_reset_success_ur': 'پاسورڈ کامیابی سے ری سیٹ ہو گیا!',
    'reset_password_en': 'Reset Password',
    'reset_password_ur': 'پاسورڈ ری سیٹ کریں',
    'back_to_en': 'Back to ',
    'back_to_ur': 'واپس ',

    // ── Splash ──
    'brand_name_en': 'Israin Solutions',
    'brand_name_ur': 'Israin Solutions',
    'tagline_en': 'Developing Beyond Imagination',
    'tagline_ur': 'تخیل سے آگے ترقی',

    // ── Onboarding ──
    'onboard_mobile_title_en': 'Best on\nMobile Data',
    'onboard_mobile_title_ur': 'موبائل ڈیٹا پر\nبہترین',
    'onboard_mobile_desc_en': 'For the best experience, use mobile data instead of WiFi. Some WiFi networks may block app connections.',
    'onboard_mobile_desc_ur': 'بہترین تجربے کے لیے، WiFi کی بجائے موبائل ڈیٹا استعمال کریں۔ کچھ WiFi نیٹ ورکس ایپ کنکشنز کو روک سکتے ہیں۔',
    'onboard_ai_title_en': 'Transforming\nBusiness with\nAgentic AI',
    'onboard_ai_title_ur': 'Agentic AI سے\nکاروبار میں\nتبدیلی',
    'onboard_ai_desc_en': 'Empower your organization with autonomous agents that streamline operations, enhance decision-making, and unlock hyper-efficiency.',
    'onboard_ai_desc_ur': 'خود کار ایجنٹس کے ساتھ اپنے تنظیم کو بااختیار بنائیں جو آپریشنز کو ہموار کرتے ہیں، فیصلہ سازی کو بہتر بناتے ہیں، اور فائق کارکردگی کو فعال کرتے ہیں۔',
    'onboard_automation_title_en': 'Intelligent\nAutomation\nat Scale',
    'onboard_automation_title_ur': 'بڑے پیمانے پر\nذہین خودکاری',
    'onboard_automation_desc_en': 'Deploy AI-powered workflows that adapt to your business needs, reducing manual overhead and accelerating growth.',
    'onboard_automation_desc_ur': 'AI سے چلنے والے workflows کو متعارف کرائیں جو آپ کی کاروباری ضروریات کے مطابق ڈھالے جاتے ہیں۔',
    'onboard_partnership_title_en': 'Your AI\nPartnership\nStarts Here',
    'onboard_partnership_title_ur': 'آپ کی AI\nشراکت\nیہاں شروع ہوتی ہے',
    'onboard_partnership_desc_en': 'Connect with our AI development and digital marketing experts to transform your vision into reality.',
    'onboard_partnership_desc_ur': 'ہمارے AI ڈویلپمنٹ اور ڈیجیٹل مارکیٹنگ ماہرین سے رابطہ کریں۔',
    'skip_en': 'Skip',
    'skip_ur': 'چھوڑیں',
    'next_step_en': 'Next Step',
    'next_step_ur': 'اگلا قدم',
    'get_started_en': 'Get Started',
    'get_started_ur': 'شروع کریں',

    // ── Home ──
    'good_morning_en': 'Good morning',
    'good_morning_ur': 'صبح بخیر',
    'good_afternoon_en': 'Good afternoon',
    'good_afternoon_ur': 'دوپہر بخیر',
    'good_evening_en': 'Good evening',
    'good_evening_ur': 'شام بخیر',
    'overview_account_en': "Here's an overview of your account",
    'overview_account_ur': 'آپ کے اکاؤنٹ کا خلاصہ',
    'total_inquiries_en': 'Total Inquiries',
    'total_inquiries_ur': 'کل انکوائریز',
    'active_chats_en': 'Active Chats',
    'active_chats_ur': 'فعال چیٹس',
    'resolved_en': 'Resolved',
    'resolved_ur': 'حل شدہ',
    'ratings_given_en': 'Ratings Given',
    'ratings_given_ur': 'دی گئی ریٹنگز',
    'recent_activity_en': 'Recent Activity',
    'recent_activity_ur': 'حالیہ سرگرمی',
    'no_recent_activity_en': 'No recent activity',
    'no_recent_activity_ur': 'کوئی حالیہ سرگرمی نہیں',
    'in_discussion_en': 'In Discussion',
    'in_discussion_ur': 'بحث میں',
    'pending_en': 'Pending',
    'pending_ur': 'زیر التوا',
    'quick_actions_en': 'Quick Actions',
    'quick_actions_ur': 'فوری افعال',
    'new_inquiry_en': 'New Inquiry',
    'new_inquiry_ur': 'نئی انکوائری',
    'chat_with_ai_en': 'Chat with AI',
    'chat_with_ai_ur': 'AI سے بات کریں',
    'faq_en': 'FAQ',
    'faq_ur': 'عمومی سوالات',
    'live_analytics_en': 'Live Analytics',
    'live_analytics_ur': 'لائیو اینالیٹکس',
    'ready_scale_en': 'Ready to scale your digital operations?',
    'ready_scale_ur': 'اپنے ڈیجیٹل آپریشنز کو بڑھانے کے لیے تیار؟',
    'manage_services_en': 'Manage Services',
    'manage_services_ur': 'سروسز کا انتظام کریں',
    'view_inquiries_en': 'View Inquiries',
    'view_inquiries_ur': 'انکوائریز دیکھیں',
    'broadcast_message_en': 'Broadcast Message',
    'broadcast_message_ur': 'خبر رسانی',
    'active_conversations_en': 'Active conversations',
    'active_conversations_ur': 'فعال گفتگو',
    'projects_delivered_en': 'Projects delivered',
    'projects_delivered_ur': 'منصوبے مکمل',
    'total_customers_en': 'Total Customers',
    'total_customers_ur': 'کل گاہک',
    'registered_users_en': 'Registered users',
    'registered_users_ur': 'رجسٹرڈ صارفین',
    'inquiry_status_en': 'Inquiry Status',
    'inquiry_status_ur': 'انکوائری کی صورتحال',
    'total_inquiries_count_en': 'total inquiries',
    'total_inquiries_count_ur': 'کل انکوائریز',
    'customers_en': 'Customers',
    'customers_ur': 'گاہک',
    'view_all_reviews_en': 'View All Reviews',
    'view_all_reviews_ur': 'تمام جائزے دیکھیں',
    'recent_reviews_en': 'Recent Reviews',
    'recent_reviews_ur': 'حالیہ جائزے',
    'customer_en': 'Customer',
    'customer_ur': 'گاہک',
    'breakdown_en': 'Breakdown',
    'breakdown_ur': 'تفصیل',
    'ai_development_en': 'AI Development',
    'ai_development_ur': 'AI ڈویلپمنٹ',
    'digital_marketing_en': 'Digital Marketing',
    'digital_marketing_ur': 'ڈیجیٹل مارکیٹنگ',
    'no_inquiries_yet_en': 'No inquiries yet',
    'no_inquiries_yet_ur': 'ابھی تک کوئی انکوائری نہیں',
    'bot_resolution_rate_en': 'Bot Resolution Rate',
    'bot_resolution_rate_ur': 'بات چیت کی حل شدہ شرح',
    'manage_inquiries_en': 'Manage Inquiries',
    'manage_inquiries_ur': 'انکوائریز کا انتظام کریں',
    'manage_inquiries_desc_en': 'View and respond to all customer inquiries',
    'manage_inquiries_desc_ur': 'تمام گاہک انکوائریز دیکھیں اور جواب دیں',
    'manage_services_desc_en': 'Create, edit, or remove services',
    'manage_services_desc_ur': 'سروسز بنائیں، ترمیم کریں، یا حذف کریں',
    'manage_orders_en': 'Manage Orders',
    'manage_orders_ur': 'ارڈرز کا انتظام کریں',
    'manage_orders_desc_en': 'View and manage all shop orders',
    'manage_orders_desc_ur': 'تمام شاپ ارڈرز دیکھیں اور ان کا انتظام کریں',
    'send_message_all_en': 'Send a message to all customers',
    'send_message_all_ur': 'تمام گاہکوں کو پیغام بھیجیں',
    'title_en': 'Title',
    'title_ur': 'عنوان',
    'title_hint_en': 'e.g. New Feature Update',
    'title_hint_ur': 'مثلاً نئی خصوصیت کی اپ ڈیٹ',
    'title_required_en': 'Title is required',
    'title_required_ur': 'عنوان ضروری ہے',
    'message_en': 'Message',
    'message_ur': 'پیغام',
    'message_hint_en': 'Write your message here...',
    'message_hint_ur': 'یہاں اپنا پیغام لکھیں...',
    'message_required_en': 'Message is required',
    'message_required_ur': 'پیغام ضوری ہے',
    'send_to_all_en': 'Send to All Customers',
    'send_to_all_ur': 'تمام گاہکوں کو بھیجیں',

    // ── Services ──
    'services_en': 'Services',
    'services_ur': 'سروسز',
    'search_services_en': 'Search services...',
    'search_services_ur': 'سروسز تلاش کریں...',
    'browse_category_en': 'Browse by Category',
    'browse_category_ur': 'زمرے سے دیکھیں',
    'why_choose_us_en': 'Why Choose Us?',
    'why_choose_us_ur': 'ہم کیوں منتخب کریں؟',
    'what_clients_say_en': 'What Our Clients Say',
    'what_clients_say_ur': 'ہمارے گاہک کیا کہتے ہیں',
    'request_service_en': 'Request Service',
    'request_service_ur': 'سروس کی درخواست کریں',
    'from_en': 'From',
    'from_ur': 'سے',
    'popular_en': 'Popular',
    'popular_ur': 'مقبول',
    'requests_en': 'requests',
    'requests_ur': 'درخواستیں',
    'service_en': 'Service',
    'service_ur': 'سروس',
    'service_loading_en': 'Service details loading...',
    'service_loading_ur': 'سروس کی تفصیلات لوڈ ہو رہی ہیں...',
    'price_en': 'Price',
    'price_ur': 'قیمت',
    'timeline_en': 'Timeline',
    'timeline_ur': 'ٹائم لائن',
    'pricing_tiers_en': 'Pricing Tiers',
    'pricing_tiers_ur': 'قیمت کے درجے',
    'starter_en': 'Starter',
    'starter_ur': 'شروعاتی',
    'pro_en': 'Pro',
    'pro_ur': 'پرو',
    'enterprise_en': 'Enterprise',
    'enterprise_ur': 'انٹرپرائز',
    'weeks_en': 'weeks',
    'weeks_ur': 'ہفتے',
    'basic_features_en': 'Basic features',
    'basic_features_ur': 'بنیادی خصوصیات',
    'email_support_en': 'Email support',
    'email_support_ur': 'ای میل سپورٹ',
    'revision_en': 'revision',
    'revision_ur': 'ترمیم',
    'full_features_en': 'Full features',
    'full_features_ur': 'مکمل خصوصیات',
    'priority_support_en': 'Priority support',
    'priority_support_ur': 'ترجیحی سپورٹ',
    'revisions_en': 'revisions',
    'revisions_ur': 'ترمیں',
    'analytics_en': 'Analytics',
    'analytics_ur': 'اینالیٹکس',
    'everything_in_pro_en': 'Everything in Pro',
    'everything_in_pro_ur': 'پرو میں سب کچھ',
    'dedicated_manager_en': 'Dedicated manager',
    'dedicated_manager_ur': 'مخصوص منتظم',
    'unlimited_revisions_en': 'Unlimited revisions',
    'unlimited_revisions_ur': 'لامحدود ترمیں',
    'sla_guarantee_en': 'SLA guarantee',
    'sla_guarantee_ur': 'SLA گارنٹی',
    'custom_en': 'Custom',
    'custom_ur': 'حسب ضرورت',
    'about_this_service_en': 'About This Service',
    'about_this_service_ur': 'اس سروس کے بارے میں',
    'use_cases_en': 'Use Cases',
    'use_cases_ur': 'استعمال کے مواقع',
    'no_services_category_en': 'No services in',
    'no_services_category_ur': 'اس زمرے میں کوئی سروس نہیں',
    'compare_services_en': 'Compare Services',
    'compare_services_ur': 'سروسز کا موازنہ کریں',
    'select_2_compare_en': 'Select 2 services to compare',
    'select_2_compare_ur': 'موازنے کے لیے 2 سروسز منتخب کریں',
    'category_en': 'Category',
    'category_ur': 'زمرہ',
    'feature_en': 'Feature',
    'feature_ur': 'خصوصیت',
    'no_use_cases_en': 'No use cases listed',
    'no_use_cases_ur': 'استعمال کے مواقع درج نہیں',

    // ── Inquiry Form ──
    'submit_inquiry_en': 'Submit Inquiry',
    'submit_inquiry_ur': 'انکوائری جمع کریں',
    'tell_about_project_en': 'Tell us about your project',
    'tell_about_project_ur': 'ہمیں اپنے منصوبے کے بارے میں بتائیں',
    'respond_24h_en': 'We typically respond within 24 hours',
    'respond_24h_ur': 'ہم عام طور پر 24 گھنٹوں میں جواب دیتے ہیں',
    'phone_optional_en': 'PHONE (OPTIONAL)',
    'phone_optional_ur': 'فون (اختیاری)',
    'phone_hint_en': '+1 (555) 000-0000',
    'phone_hint_ur': '+92 300 0000000',
    'service_type_en': 'SERVICE TYPE',
    'service_type_ur': 'سروس کی قسم',
    'budget_en': 'BUDGET',
    'budget_ur': 'بجٹ',
    'select_budget_en': 'Select budget range',
    'select_budget_ur': 'بجٹ کی رینج منتخب کریں',
    'budget_100_500_en': '\$100 - \$500',
    'budget_100_500_ur': '\$100 - \$500',
    'budget_500_1000_en': '\$500 - \$1,000',
    'budget_500_1000_ur': '\$500 - \$1,000',
    'budget_1000_plus_en': '\$1,000+',
    'budget_1000_plus_ur': '\$1,000+',
    'delivery_priority_en': 'DELIVERY PRIORITY',
    'delivery_priority_ur': 'ڈلیوری کی ترجیح',
    'urgent_fast_en': 'Urgent / Fast Delivery',
    'urgent_fast_ur': 'فوری / تیز ڈلیوری',
    'standard_time_en': 'Standard Time',
    'standard_time_ur': 'معمولی وقت',
    'your_message_en': 'YOUR MESSAGE',
    'your_message_ur': 'آپ کا پیغام',
    'message_hint_form_en': 'Tell us about your project requirements...',
    'message_hint_form_ur': 'ہمیں اپنی پروجیکٹ کی ضروریات بتائیں...',
    'select_budget_error_en': 'Please select a budget range',
    'select_budget_error_ur': 'براہ کرم بجٹ کی رینج منتخب کریں',
    'thank_you_en': 'Thank You!',
    'thank_you_ur': 'شکریہ!',
    'thanks_submit_en': 'Thanks for submitting your request, our team will look into this and get back to you as soon as possible.',
    'thanks_submit_ur': 'آپ کی درخواست جمع کرنے کا شکریہ، ہماری ٹیم اس پر نظر رکھے گی اور جلد آپ کو جواب دے گی۔',
    'discuss_now_en': 'Want to discuss right now?',
    'discuss_now_ur': 'ابھی بات کرنا چاہتے ہیں؟',
    'chat_with_ai_bot_en': 'Chat with AI Bot',
    'chat_with_ai_bot_ur': 'AI بات چیت سے بات کریں',
    'chat_with_team_en': 'Chat with Team',
    'chat_with_team_ur': 'ٹیم سے بات کریں',
    'back_to_home_en': 'Back to Home',
    'back_to_home_ur': 'ہوم پر واپس',

    // ── Shop ──
    'shop_en': 'Shop',
    'shop_ur': 'شاپ',
    'graphics_en': 'Graphics',
    'graphics_ur': 'گرافکس',
    'web_en': 'Web',
    'web_ur': 'ویب',
    'marketing_en': 'Marketing',
    'marketing_ur': 'مارکیٹنگ',
    'animation_en': 'Animation',
    'animation_ur': 'اینیمیشن',
    'product_en': 'Product',
    'product_ur': 'پروڈکٹ',
    'order_now_en': 'Order Now',
    'order_now_ur': 'ابھی آرڈر کریں',
    'failed_load_shop_en': 'Failed to load shop items',
    'failed_load_shop_ur': 'شاپ آئٹمز لوڈ کرنے میں ناکامی',
    'no_items_category_en': 'No items in this category',
    'no_items_category_ur': 'اس زمرے میں کوئی آئٹم نہیں',
    'check_back_later_en': 'Check back later for new products.',
    'check_back_later_ur': 'نئے پروڈکٹس کے لیے بعد میں دیکھیں۔',

    // ── Product Detail ──
    'select_payment_en': 'Select Payment Method',
    'select_payment_ur': 'ادائیگی کا طریقہ منتخب کریں',
    'total_en': 'Total',
    'total_ur': 'کل',
    'cash_on_delivery_en': 'Cash on Delivery',
    'cash_on_delivery_ur': 'ڈلیوری پر ادائیگی',
    'cash_on_delivery_desc_en': 'Pay when order is delivered',
    'cash_on_delivery_desc_ur': 'ارڈر ڈلیور ہونے پر ادائیگی کریں',
    'pay_with_paypal_en': 'Pay with PayPal',
    'pay_with_paypal_ur': 'PayPal سے ادائیگی کریں',
    'paypal_desc_en': 'Pay securely with your PayPal account',
    'paypal_desc_ur': 'اپنے PayPal اکاؤنٹ سے محفوظ طریقے سے ادائیگی کریں',
    'could_not_start_paypal_en': 'Could not start PayPal checkout',
    'could_not_start_paypal_ur': 'PayPal چیک آؤٹ شروع نہیں ہو سکا',
    'could_not_open_paypal_en': 'Could not open PayPal',
    'could_not_open_paypal_ur': 'PayPal نہیں کھلا',
    'payment_cancelled_en': 'Payment cancelled',
    'payment_cancelled_ur': 'ادائیگی منسوخ',
    'payment_failed_en': 'Payment failed',
    'payment_failed_ur': 'ادائیگی ناکام',
    'paypal_payment_en': 'PayPal Payment',
    'paypal_payment_ur': 'PayPal ادائیگی',
    'paypal_complete_desc_en': 'Complete your payment on the PayPal page. When you are done, come back here and tap "I Completed Payment" to finish your order.',
    'paypal_complete_desc_ur': 'PayPal صفحے پر ادائیگی مکمل کریں۔ جب ہو جائے تو یہاں واپس آئیں اور "ادائیگی مکمل" دبائیں۔',
    'i_completed_payment_en': 'I Completed Payment',
    'i_completed_payment_ur': 'ادائیگی مکمل ہو گئی',
    'order_placed_en': 'Order Placed!',
    'order_placed_ur': 'آرڈر رکھ دیا گیا!',
    'paypal_success_desc_en': 'Payment received via PayPal. Our team will review your order and get back to you shortly.',
    'paypal_success_desc_ur': 'PayPal کے ذریعے ادائیگی موصول ہو گئی۔ ہماری ٹیم آپ کے آرڈر کا جائزہ لے گی اور جلد آپ کو جواب دے گی۔',
    'order_review_desc_en': 'Our team will review your order and get back to you shortly.',
    'order_review_desc_ur': 'ہماری ٹیم آپ کے آرڈر کا جائزہ لے گی اور جلد آپ کو جواب دے گی۔',
    'view_orders_en': 'View Orders',
    'view_orders_ur': 'ارڈرز دیکھیں',
    'continue_shopping_en': 'Continue Shopping',
    'continue_shopping_ur': 'خریداری جاری رکھیں',
    'starting_price_en': 'Starting Price',
    'starting_price_ur': 'شروعاتی قیمت',
    'delivery_en': 'Delivery',
    'delivery_ur': 'ڈلیوری',
    'description_en': 'Description',
    'description_ur': 'تفصیل',
    'whats_included_en': "What's Included",
    'whats_included_ur': 'کیا شامل ہے',
    'quantity_en': 'Quantity',
    'quantity_ur': 'مقدار',
    'special_requirements_en': 'Special Requirements',
    'special_requirements_ur': 'خصوصی ضروریات',
    'special_requirements_hint_en': 'Any specific requirements or instructions...',
    'special_requirements_hint_ur': 'کوئی مخصوص ضروریات یا ہدایات...',
    'order_now_total_en': 'Order Now',
    'order_now_total_ur': 'ابھی آرڈر کریں',

    // ── My Orders ──
    'my_orders_en': 'My Orders',
    'my_orders_ur': 'میرے ارڈرز',
    'pending_status_en': 'PENDING',
    'pending_status_ur': 'زیر التوا',
    'accepted_en': 'ACCEPTED',
    'accepted_ur': 'قبول شدہ',
    'in_progress_en': 'IN PROGRESS',
    'in_progress_ur': 'جاری',
    'delivered_en': 'DELIVERED',
    'delivered_ur': 'ڈلیور شدہ',
    'cancelled_en': 'CANCELLED',
    'cancelled_ur': 'منسوخ شدہ',
    'cancel_order_en': 'Cancel Order',
    'cancel_order_ur': 'آرڈر منسوخ کریں',
    'cancel_order_confirm_en': 'Are you sure you want to cancel this order?',
    'cancel_order_confirm_ur': 'کیا آپ واقعی یہ آرڈر منسوخ کرنا چاہتے ہیں؟',
    'yes_cancel_en': 'Yes, Cancel',
    'yes_cancel_ur': 'ہاں، منسوخ کریں',
    'order_cancelled_en': 'Order cancelled',
    'order_cancelled_ur': 'آرڈر منسوخ',
    'failed_cancel_order_en': 'Failed to cancel order',
    'failed_cancel_order_ur': 'آرڈر منسوخ کرنے میں ناکامی',
    'qty_en': 'Qty',
    'qty_ur': 'مقدار',
    'failed_load_orders_en': 'Failed to load orders',
    'failed_load_orders_ur': 'ارڈرز لوڈ کرنے میں ناکامی',
    'no_orders_yet_en': 'No orders yet',
    'no_orders_yet_ur': 'ابھی تک کوئی آرڈر نہیں',
    'first_order_desc_en': 'Place your first order from the shop.',
    'first_order_desc_ur': 'شاپ سے اپنا پہلا آرڈر لگائیں۔',
    'browse_shop_en': 'Browse Shop',
    'browse_shop_ur': 'شاپ دیکھیں',

    // ── Chat ──
    'chat_with_ai_title_en': 'Chat with AI',
    'chat_with_ai_title_ur': 'AI سے بات کریں',
    'powered_by_en': 'Powered by Israin Intelligence',
    'powered_by_ur': 'Israin Intelligence کے ساتھ',
    'setup_thanks_en': "I'm setting things up. Please try again in a moment.",
    'setup_thanks_ur': 'میں ترتیبات دے رہا ہوں۔ براہ کرم دیر سے دوبارہ کوشش کریں۔',
    'team_notified_en': "Our team has been notified! They'll respond shortly.",
    'team_notified_ur': 'ہماری ٹیم کو اطلاع دے دی گئی! وہ جلد جواب دیں گے۔',
    'something_wrong_en': 'Something went wrong. Please try again.',
    'something_wrong_ur': 'کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔',
    'team_notified_short_en': "Our team will be notified. They'll respond shortly!",
    'team_notified_short_ur': 'ہماری ٹیم کو اطلاع دی جائے گی۔ وہ جلد جواب دیں گے!',
    'talk_to_human_en': 'Talk to\nHuman',
    'talk_to_human_ur': 'انسان سے\nبات کریں',
    'thinking_en': 'Thinking...',
    'thinking_ur': 'سوچ رہا ہے...',
    'pricing_info_en': 'Pricing info',
    'pricing_info_ur': 'قیمت کی معلومات',
    'timelines_en': 'Timelines',
    'timelines_ur': 'ٹائم لائن',
    'our_services_en': 'Our services',
    'our_services_ur': 'ہماری سروسز',
    'talk_to_team_en': 'Talk to team',
    'talk_to_team_ur': 'ٹیم سے بات کریں',
    'type_message_en': 'Type your message...',
    'type_message_ur': 'اپنا پیغام لکھیں...',
    'customer_chat_en': 'Customer Chat',
    'customer_chat_ur': 'گاہک چیٹ',
    'support_team_en': 'Support Team',
    'support_team_ur': 'سپورٹ ٹیم',
    'online_replies_en': 'Online • Typically replies in minutes',
    'online_replies_ur': 'آنلائن • عام طور پر منٹوں میں جواب',
    'search_messages_en': 'Search messages',
    'search_messages_ur': 'پیغامات تلاش کریں',
    'search_messages_hint_en': 'Search messages...',
    'search_messages_hint_ur': 'پیغامات تلاش کریں...',
    'no_messages_search_en': 'No messages match your search',
    'no_messages_search_ur': 'آپ کی تلاش سے کوئی پیغام مماثل نہیں',
    'start_conversation_en': 'Start the conversation',
    'start_conversation_ur': 'گفتگو شروع کریں',
    'is_typing_en': 'is typing',
    'is_typing_ur': 'لکھ رہا ہے',
    'escalated_human_en': 'Escalated to human agent',
    'escalated_human_ur': 'انسان ایجینٹ کو بھیج دیا',
    'reply_customer_en': 'Reply to customer...',
    'reply_customer_ur': 'گاہک کو جواب دیں...',
    'file_too_large_en': 'File size exceeds 10MB limit',
    'file_too_large_ur': 'فائل کا سائز 10MB کی حد سے زیادہ ہے',
    'upload_failed_en': 'Upload failed',
    'upload_failed_ur': 'اپلوڈ ناکام',
    'pick_file_failed_en': 'Failed to pick file',
    'pick_file_failed_ur': 'فائل منتخب کرنے میں ناکامی',
    'ai_chat_welcome_en': "Hello! I'm the Israin Intelligence Assistant. How can I help you with our AI Development and Digital Marketing services? Ask me about pricing, timelines, or anything else!",
    'ai_chat_welcome_ur': 'ہیلو! میں Israin Intelligence اسسٹنٹ ہوں۔ میں آپ کی AI ڈویلپمنٹ اور ڈیجیٹل مارکیٹنگ سروسز میں کیسے مدد کر سکتا ہوں؟ قیمت، ٹائم لائن، یا کسی بھی چیز کے بارے میں پوچھیں!',
    'chat_welcome_en': "Hello! Welcome to Israin Solutions. How can we help you today?",
    'chat_welcome_ur': 'ہیلو! Israin Solutions میں خوش آمدید۔ آج ہم آپ کی کیسے مدد کر سکتے ہیں؟',

    // ── AI Chat History ──
    'ai_chat_history_en': 'AI Chat History',
    'ai_chat_history_ur': 'AI چیٹ کی تاریخ',
    'no_chat_history_en': 'No chat history yet',
    'no_chat_history_ur': 'ابھی تک کوئی چیٹ تاریخ نہیں',
    'start_ai_conversation_en': 'Start a conversation with AI Assistant',
    'start_ai_conversation_ur': 'AI اسسٹنٹ سے گفتگو شروع کریں',
    'escalated_en': 'Escalated',
    'escalated_ur': 'بھیج دیا',

    // ── Profile ──
    'account_settings_en': 'ACCOUNT SETTINGS',
    'account_settings_ur': 'اکاؤنٹ ترتیبات',
    'personal_details_en': 'Personal Details',
    'personal_details_ur': 'ذاتی تفصیلات',
    'customer_dashboard_en': 'Customer Dashboard',
    'customer_dashboard_ur': 'گاہک ڈیش بورڈ',
    'company_profile_en': 'Company Profile',
    'company_profile_ur': 'کمپنی پروفائل',
    'preferences_en': 'PREFERENCES',
    'preferences_ur': 'ترجیحات',
    'dark_mode_en': 'Dark Mode',
    'dark_mode_ur': 'ڈارک موڈ',
    'dark_active_en': 'Dark theme active',
    'dark_active_ur': 'ڈارک تھیم فعال',
    'light_active_en': 'Light theme active',
    'light_active_ur': 'لائٹ تھیم فعال',
    'language_en': 'Language',
    'language_ur': 'زبان',
    'english_en': 'English',
    'english_ur': 'انگریزی',
    'urdu_en': 'Urdu',
    'urdu_ur': 'اردو',
    'two_factor_auth_en': 'Two-Factor Auth',
    'two_factor_auth_ur': 'دو مرحلہ تصدیق',
    'two_factor_desc_en': 'Extra security for your account',
    'two_factor_desc_ur': 'آپ کے اکاؤنٹ کے لیے اضافی سیکیورٹی',
    'legal_en': 'LEGAL',
    'legal_ur': 'قانونی',
    'privacy_policy_en': 'Privacy Policy',
    'privacy_policy_ur': 'رازداری کی پالیسی',
    'terms_of_service_en': 'Terms of Service',
    'terms_of_service_ur': 'سروس کی شرائط',
    'logout_en': 'Logout',
    'logout_ur': 'لاگ آؤٹ',
    'edit_profile_en': 'Edit Profile',
    'edit_profile_ur': 'پروفائل میں ترمیم',
    'name_en': 'NAME',
    'name_ur': 'نام',
    'phone_en': 'PHONE',
    'phone_ur': 'فون',
    'save_changes_en': 'Save Changes',
    'save_changes_ur': 'تبدیلیاں محفوظ کریں',
    'my_orders_item_en': 'My Orders',
    'my_orders_item_ur': 'میرے ارڈرز',
    'ai_chat_history_item_en': 'AI Chat History',
    'ai_chat_history_item_ur': 'AI چیٹ کی تاریخ',
    'version_en': 'Version 1.0.0',
    'version_ur': 'ورژن 1.0.0',
    'lang_display_en': 'English',
    'lang_display_ur': 'اردو (Urdu)',
    'two_fa_enabled_en': '2FA enabled',
    'two_fa_enabled_ur': '2FA فعال',
    'two_fa_disabled_en': '2FA disabled',
    'two_fa_disabled_ur': '2FA غیر فعال',
    'logout_confirm_en': 'Are you sure you want to logout?',
    'logout_confirm_ur': 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
    'profile_updated_en': 'Profile updated',
    'profile_updated_ur': 'پروفائل اپ ڈیٹ',
    'failed_update_en': 'Failed to update',
    'failed_update_ur': 'اپ ڈیٹ میں ناکامی',

    // ── FAQ ──
    'faq_search_hint_en': 'Search questions...',
    'faq_search_hint_ur': 'سوالات تلاش کریں...',
    'no_results_en': 'No results found',
    'no_results_ur': 'کوئی نتائج نہیں ملے',
    'services_category_en': 'Services',
    'services_category_ur': 'سروسز',
    'process_category_en': 'Process',
    'process_category_ur': 'عمل',
    'account_category_en': 'Account',
    'account_category_ur': 'اکاؤنٹ',
    'payments_category_en': 'Payments',
    'payments_category_ur': 'ادائیگیاں',

    // ── Company Profile ──
    'location_en': 'Location',
    'location_ur': 'مقام',
    'lahore_pakistan_en': 'Lahore, Pakistan',
    'lahore_pakistan_ur': 'لاہور، پاکستان',
    'email_en': 'Email',
    'email_ur': 'ای میل',
    'website_en': 'Website',
    'website_ur': 'ویب سائٹ',
    'founded_en': 'Founded',
    'founded_ur': 'قائم شدہ',
    'projects_completed_en': 'Projects\nCompleted',
    'projects_completed_ur': 'منصوبے\nمکمل',
    'team_members_en': 'Team\nMembers',
    'team_members_ur': 'ٹیم\nممبران',
    'client_satisfaction_en': 'Client\nSatisfaction',
    'client_satisfaction_ur': 'گاہک\nاطمینان',
    'about_us_en': 'About Us',
    'about_us_ur': 'ہمارے بارے میں',
    'about_us_desc_en': 'Israin Solutions is a forward-thinking technology company specializing in AI development and digital marketing. We build custom AI agents, chatbots, and automation solutions that transform how businesses operate.',
    'about_us_desc_ur': 'Israin Solutions ایک جدید ٹیکنالوجی کمپنی ہے جو AI ڈویلپمنٹ اور ڈیجیٹل مارکیٹنگ میں مہارت رکھتی ہے۔ ہم کسٹم AI ایجنٹس، چیٹ بوٹس، اور خودکار حل بناتے ہیں جو کاروبار کے چلنے کے طریقے کو بدل دیتے ہیں۔',
    'our_services_section_en': 'Our Services',
    'our_services_section_ur': 'ہماری سروسز',
    'custom_ai_agents_en': 'Custom AI agents, chatbots, automation',
    'custom_ai_agents_ur': 'کسٹم AI ایجنٹس، چیٹ بوٹس، خودکاری',
    'seo_sem_social_en': 'SEO, SEM, social media, content',
    'seo_sem_social_ur': 'SEO، SEM، سوشل میڈیا، مواد',

    // ── Admin Services ──
    'failed_load_services_en': 'Failed to load services',
    'failed_load_services_ur': 'سروسز لوڈ کرنے میں ناکامی',
    'delete_service_en': 'Delete Service',
    'delete_service_ur': 'سروس حذف کریں',
    'delete_confirm_en': 'Are you sure you want to delete',
    'delete_confirm_ur': 'کیا آپ واقعی حذف کرنا چاہتے ہیں',
    'service_deleted_en': 'Service deleted',
    'service_deleted_ur': 'سروس حذف',
    'failed_delete_en': 'Failed to delete',
    'failed_delete_ur': 'حذف کرنے میں ناکامی',
    'manage_services_title_en': 'Manage Services',
    'manage_services_title_ur': 'سروسز کا انتظام',
    'no_services_yet_en': 'No services yet',
    'no_services_yet_ur': 'ابھی تک کوئی سروس نہیں',
    'tap_plus_create_en': 'Tap + to create your first service',
    'tap_plus_create_ur': 'اپنی پہلی سروس بنانے کے لیے + دبائیں',
    'edit_service_en': 'Edit Service',
    'edit_service_ur': 'سروس میں ترمیم',
    'create_service_en': 'Create Service',
    'create_service_ur': 'سروس بنائیں',
    'service_name_en': 'SERVICE NAME',
    'service_name_ur': 'سروس کا نام',
    'service_name_hint_en': 'e.g. AI Chatbots',
    'service_name_hint_ur': 'مثلاً AI چیٹ بوٹس',
    'category_label_en': 'CATEGORY',
    'category_label_ur': 'زمرہ',
    'describe_service_en': 'Describe the service...',
    'describe_service_ur': 'سروس کی وضاحت کریں...',
    'price_label_en': 'PRICE (\$)',
    'price_label_ur': 'قیمت (\$)',
    'timeline_label_en': 'TIMELINE',
    'timeline_label_ur': 'ٹائم لائن',
    'timeline_hint_en': 'e.g. 2-4 weeks',
    'timeline_hint_ur': 'مثلاً 2-4 ہفتے',
    'use_cases_label_en': 'USE CASES (comma separated)',
    'use_cases_label_ur': 'استعمال کے مواقع (کوما سے الگ)',
    'use_cases_hint_en': 'e.g. E-commerce, Healthcare, Finance',
    'use_cases_hint_ur': 'مثلاً ای کامرس، ہیلتھ کیئر، فائنا',
    'update_service_en': 'Update Service',
    'update_service_ur': 'سروس اپ ڈیٹ',
    'failed_save_service_en': 'Failed to save service',
    'failed_save_service_ur': 'سروس محفوظ کرنے میں ناکامی',

    // ── Admin Orders ──
    'order_status_updated_en': 'Order status updated to',
    'order_status_updated_ur': 'آرڈر کی صورتحال اپ ڈیٹ',
    'failed_update_status_en': 'Failed to update status',
    'failed_update_status_ur': 'صورتحال اپ ڈیٹ میں ناکامی',
    'order_details_en': 'Order Details',
    'order_details_ur': 'آرڈر کی تفصیلات',
    'item_en': 'Item',
    'item_ur': 'آئٹم',
    'requirements_en': 'Requirements',
    'requirements_ur': 'ضروریات',
    'date_en': 'Date',
    'date_ur': 'تاریخ',
    'update_status_en': 'Update Status',
    'update_status_ur': 'صورتحال اپ ڈیٹ',
    'accept_en': 'Accept',
    'accept_ur': 'قبول کریں',
    'start_en': 'Start',
    'start_ur': 'شروع کریں',
    'deliver_en': 'Deliver',
    'deliver_ur': 'ڈلیور کریں',
    'orders_en': 'Orders',
    'orders_ur': 'ارڈرز',
    'no_orders_found_en': 'No orders found',
    'no_orders_found_ur': 'کوئی آرڈرز نہیں ملے',
    'orders_appear_en': 'Orders will appear here once customers place them.',
    'orders_appear_ur': 'گاہکوں کے آرڈر لگاتے ہیں تو یہاں دکھائیں گے۔',
    'no_filter_orders_en': 'No',
    'no_filter_orders_ur': 'کوئی',

    // ── Admin Inquiries ──
    'status_updated_to_en': 'Status updated to',
    'status_updated_to_ur': 'صورتحال اپ ڈیٹ',
    'inquiry_resolved_en': 'Inquiry marked as resolved',
    'inquiry_resolved_ur': 'انکوائری حل شدہ نشان لگا',
    'failed_resolve_en': 'Failed to resolve inquiry',
    'failed_resolve_ur': 'انکوائری حل کرنے میں ناکامی',
    'inquiry_label_en': 'Inquiry:',
    'inquiry_label_ur': 'انکوائری:',
    'new_status_en': 'New',
    'new_status_ur': 'نیا',
    'in_discussion_status_en': 'In Discussion',
    'in_discussion_status_ur': 'بحث میں',
    'resolved_status_en': 'Resolved',
    'resolved_status_ur': 'حل شدہ',
    'cancelled_status_en': 'Cancelled',
    'cancelled_status_ur': 'منسوخ شدہ',
    'mark_resolved_en': 'Mark Resolved',
    'mark_resolved_ur': 'حل شدہ نشان لگائیں',
    'notes_en': 'Notes',
    'notes_ur': 'نوٹس',
    'add_en': 'Add',
    'add_ur': 'شامل کریں',
    'no_notes_yet_en': 'No notes yet',
    'no_notes_yet_ur': 'ابھی تک کوئی نوٹس نہیں',
    'add_note_en': 'Add Note',
    'add_note_ur': 'نوٹ شامل کریں',
    'write_note_en': 'Write your note...',
    'write_note_ur': 'اپنا نوٹ لکھیں...',
    'note_added_en': 'Note added',
    'note_added_ur': 'نوٹ شامل',
    'failed_add_note_en': 'Failed to add note',
    'failed_add_note_ur': 'نوٹ شامل کرنے میں ناکامی',
    'all_inquiries_en': 'All Inquiries',
    'all_inquiries_ur': 'تمام انکوائریز',
    'manage_respond_en': 'Manage and respond to customer inquiries.',
    'manage_respond_ur': 'گاہک انکوائریز کا انتظام کریں اور جواب دیں۔',
    'no_inquiries_found_en': 'No inquiries found',
    'no_inquiries_found_ur': 'کوئی انکوائریز نہیں ملیں',
    'reply_en': 'Reply',
    'reply_ur': 'جواب دیں',
    'new_filter_en': 'New',
    'new_filter_ur': 'نئی',

    // ── My Inquiries ──
    'my_inquiries_en': 'My Inquiries',
    'my_inquiries_ur': 'میری انکوائریز',
    'track_manage_en': 'Track and manage your ongoing AI project collaborations.',
    'track_manage_ur': 'اپنے جاری AI منصوبے کے تعاون کو ٹریک اور انتظام کریں۔',
    'failed_load_inquiries_en': 'Failed to load inquiries',
    'failed_load_inquiries_ur': 'انکوائریز لوڈ کرنے میں ناکامی',
    'no_inquiries_yet_customer_en': 'No inquiries yet',
    'no_inquiries_yet_customer_ur': 'ابھی تک کوئی انکوائری نہیں',
    'first_inquiry_desc_en': 'Submit your first inquiry to get started.',
    'first_inquiry_desc_ur': 'شروع کرنے کے لیے اپنی پہلی انکوائری جمع کریں۔',
    'need_something_new_en': 'Need to start something new?',
    'need_something_new_ur': 'کچھ نیا شروع کرنا ہے؟',
    'submit_new_inquiry_en': 'Submit New Inquiry',
    'submit_new_inquiry_ur': 'نئی انکوائری جمع کریں',
    'submitted_on_en': 'Submitted on',
    'submitted_on_ur': 'جمع کیا',
    'cancel_inquiry_en': 'Cancel Inquiry',
    'cancel_inquiry_ur': 'انکوائری منسوخ کریں',
    'cancel_inquiry_confirm_en': 'Are you sure you want to cancel this inquiry?',
    'cancel_inquiry_confirm_ur': 'کیا آپ واقعی یہ انکوائری منسوخ کرنا چاہتے ہیں؟',
    'failed_cancel_inquiry_en': 'Failed to cancel inquiry',
    'failed_cancel_inquiry_ur': 'انکوائری منسوخ کرنے میں ناکامی',
    'your_rating_en': 'Your Rating',
    'your_rating_ur': 'آپ کی ریٹنگ',
    'rate_service_en': 'Rate Service',
    'rate_service_ur': 'سروس کی ریٹنگ کریں',
    'optional_review_en': 'Optional review',
    'optional_review_ur': 'اختیاری جائزہ',
    'failed_submit_rating_en': 'Failed to submit rating',
    'failed_submit_rating_ur': 'ریٹنگ جمع کرنے میں ناکامی',
    'view_details_en': 'View Details',
    'view_details_ur': 'تفصیلات دیکھیں',
    'open_conversation_en': 'Open Conversation',
    'open_conversation_ur': 'گفتگو کھولیں',

    // ── Privacy Policy ──
    'last_updated_en': 'Last updated: July 2026',
    'last_updated_ur': 'آخری اپ ڈیٹ: جولائی 2026',
  };

  static String t(String key) {
    final lookupKey = '${key}_$_currentLanguage';
    return _strings[lookupKey] ?? key;
  }
}
